In [59]:
#TASK 1 - Lexicons
# Lexicon -> collection of words/Phrases + Information (POS; tense Definitions..)
# Lexicon has lexical entries -> each entry is Word/Phrase -> has a HeadWord(Lemma) + Information

#1. Stopwords:
from nltk.corpus import stopwords
stopwords.words('french')

['au',
 'aux',
 'avec',
 'ce',
 'ces',
 'dans',
 'de',
 'des',
 'du',
 'elle',
 'en',
 'et',
 'eux',
 'il',
 'ils',
 'je',
 'la',
 'le',
 'les',
 'leur',
 'lui',
 'ma',
 'mais',
 'me',
 'même',
 'mes',
 'moi',
 'mon',
 'ne',
 'nos',
 'notre',
 'nous',
 'on',
 'ou',
 'par',
 'pas',
 'pour',
 'qu',
 'que',
 'qui',
 'sa',
 'se',
 'ses',
 'son',
 'sur',
 'ta',
 'te',
 'tes',
 'toi',
 'ton',
 'tu',
 'un',
 'une',
 'vos',
 'votre',
 'vous',
 'c',
 'd',
 'j',
 'l',
 'à',
 'm',
 'n',
 's',
 't',
 'y',
 'été',
 'étée',
 'étées',
 'étés',
 'étant',
 'étante',
 'étants',
 'étantes',
 'suis',
 'es',
 'est',
 'sommes',
 'êtes',
 'sont',
 'serai',
 'seras',
 'sera',
 'serons',
 'serez',
 'seront',
 'serais',
 'serait',
 'serions',
 'seriez',
 'seraient',
 'étais',
 'était',
 'étions',
 'étiez',
 'étaient',
 'fus',
 'fut',
 'fûmes',
 'fûtes',
 'furent',
 'sois',
 'soit',
 'soyons',
 'soyez',
 'soient',
 'fusse',
 'fusses',
 'fût',
 'fussions',
 'fussiez',
 'fussent',
 'ayant',
 'ayante',
 'ayantes',


In [5]:
#2. CMU WordList
import nltk
entries = nltk.corpus.cmudict.entries()
len(entries)

133737

In [6]:
entries[:50]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [7]:
#3. Wordnet
from nltk.corpus import wordnet as wn
wn.synsets('room')

[Synset('room.n.01'),
 Synset('room.n.02'),
 Synset('room.n.03'),
 Synset('room.n.04'),
 Synset('board.v.02')]

In [8]:
wn.synsets('bank')

[Synset('bank.n.01'),
 Synset('depository_financial_institution.n.01'),
 Synset('bank.n.03'),
 Synset('bank.n.04'),
 Synset('bank.n.05'),
 Synset('bank.n.06'),
 Synset('bank.n.07'),
 Synset('savings_bank.n.02'),
 Synset('bank.n.09'),
 Synset('bank.n.10'),
 Synset('bank.v.01'),
 Synset('bank.v.02'),
 Synset('bank.v.03'),
 Synset('bank.v.04'),
 Synset('bank.v.05'),
 Synset('deposit.v.02'),
 Synset('bank.v.07'),
 Synset('trust.v.01')]

In [10]:
wn.synset('bank.n.02').lemma_names()

['depository_financial_institution',
 'bank',
 'banking_concern',
 'banking_company']

In [11]:
wn.synsets('better')

[Synset('better.n.01'),
 Synset('bettor.n.01'),
 Synset('better.n.03'),
 Synset('better.n.04'),
 Synset('better.v.01'),
 Synset('better.v.02'),
 Synset('better.v.03'),
 Synset('better.a.01'),
 Synset('better.a.02'),
 Synset('better.s.03'),
 Synset('better.s.04'),
 Synset('good.a.01'),
 Synset('full.s.06'),
 Synset('good.a.03'),
 Synset('estimable.s.02'),
 Synset('beneficial.s.01'),
 Synset('good.s.06'),
 Synset('good.s.07'),
 Synset('adept.s.01'),
 Synset('good.s.09'),
 Synset('dear.s.02'),
 Synset('dependable.s.04'),
 Synset('good.s.12'),
 Synset('good.s.13'),
 Synset('effective.s.04'),
 Synset('good.s.15'),
 Synset('good.s.16'),
 Synset('good.s.17'),
 Synset('good.s.18'),
 Synset('good.s.19'),
 Synset('good.s.20'),
 Synset('good.s.21'),
 Synset('well.a.01'),
 Synset('good.s.13'),
 Synset('well.s.03'),
 Synset('better.r.01'),
 Synset('better.r.02'),
 Synset('well.r.01'),
 Synset('well.r.02'),
 Synset('well.r.03'),
 Synset('well.r.04'),
 Synset('well.r.05'),
 Synset('well.r.06'),
 Syns

In [12]:
wn.synset('better.n.01').lemma_names()

['better']

In [25]:
# Task 2 - Simple Text Classifier
def gender_features(word):
    return {'last_letter':word[-1]}

In [26]:
gender_features('Jit')

{'last_letter': 't'}

In [33]:
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
[(name, 'female') for name in names.words('female.txt')])

In [32]:
import random
random.shuffle(labeled_names)

In [34]:
featuresets = [(gender_features(n), gender) for (n, gender) in labeled_names]

In [35]:
train_set, test_set = featuresets[1000:], featuresets[:1000]

In [36]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [37]:
classifier.classify(gender_features('Donald'))

'male'

In [40]:
classifier.classify(gender_features('Susan'))

'female'

In [41]:
print(nltk.classify.accuracy(classifier, test_set))

0.461


In [26]:
# Tool names for positive and negative
#TEXTBLOB
#Jensen
# CMU Sphinx

In [42]:
# TASK 3 - Vectorisers & COSINE SIMILARITY
# CountVectorizer - Learn
# TfidfVectorizer
# from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [44]:
# fit method vectorizes all the unique words in the corpus
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [45]:
vocabul = vect.vocabulary_

In [47]:
for key in sorted(vocabul.keys()):
    print("{}:{}".format(key, vocabul[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [33]:
# do plagarism task using vectorization

In [54]:
print(vect.transform(["Following is the list of sentences tokenized from the sample review"]).toarray())

[[0 0 0 1 0 0 0 0]]


In [55]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 1 0]]


In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), 
                               vect.transform(["Following is the list of sentences tokenized from the sample review"]).toarray())

In [58]:
print(similarity[0][0])

0.5


In [1]:
#IMPORT
import nltk 
from nltk.stem import PorterStemmer 
from nltk.corpus import brown

In [3]:
#FIELDS IN BROWN CORPUS
brown.fileids()[:20]

['ca01',
 'ca02',
 'ca03',
 'ca04',
 'ca05',
 'ca06',
 'ca07',
 'ca08',
 'ca09',
 'ca10',
 'ca11',
 'ca12',
 'ca13',
 'ca14',
 'ca15',
 'ca16',
 'ca17',
 'ca18',
 'ca19',
 'ca20']

In [5]:
#we are taking reviews from brown corpus 
text_b = brown.words('ca20')

In [6]:
#length of our text file 
len(text_b)

2317

In [7]:
print(text_b)

['London', ',', 'Feb.', '9', '--', 'Vital', 'secrets', ...]


In [9]:
#frequency distribution 
freqdist = nltk.FreqDist(w.lower() for w in text_b)

freqdist

FreqDist({',': 169, 'the': 139, '.': 85, 'and': 65, 'of': 60, 'a': 50, 'in': 49, 'to': 42, 'was': 32, 'for': 27, ...})

In [10]:
#conditional frequency distribution 
from nltk.probability import ConditionalFreqDist 
fcd=ConditionalFreqDist((len(word),word) for word in text_b) 


In [11]:
fcd[2]

FreqDist({'of': 59, 'in': 44, 'to': 42, 'on': 17, '``': 16, "''": 16, 'he': 14, 'at': 11, 'by': 9, 'as': 8, ...})

In [12]:
fcd[3]

FreqDist({'the': 119, 'and': 65, 'was': 32, 'for': 27, 'The': 20, 'her': 12, 'his': 10, 'had': 8, 'two': 8, 'who': 7, ...})

In [15]:
#1)converting list to string and tokenizing 
from nltk.tokenize import sent_tokenize
#converting list to single string str1
string=" ".join(text_b)
tokenized=sent_tokenize(string)
print(tokenized)

["London , Feb. 9 -- Vital secrets of Britain's first atomic submarine , the Dreadnought , and , by implication , of the entire United States navy's still-building nuclear sub fleet , were stolen by a London-based soviet spy ring , secret service agents testified today .", 'The Dreadnought was built on designs supplied by the United States in 1959 and was launched last year .', 'It is a killer sub -- that is , a hunter of enemy subs .', "It has a hull patterned on that of the United States navy's Nautilus , the world's first atomic submarine .", 'Its power unit , however , was derived from the reactor of the more modern American nuclear submarine Skipjack .', 'Five held for trial The announcement that the secrets of the Dreadnought had been stolen was made in Bow St. police court here at the end of a three day hearing .', 'A full trial was ordered for : Two British civil servants , Miss Ethel Gee , 46 , and her newly devoted friend , Harry Houghton , 55 , and divorced .', 'They are acc

In [14]:
#POS tagging
str1 = string

tokenizeds=nltk.word_tokenize(str1)
print(tokenizeds)

tagged = nltk.pos_tag(tokenizeds)
print(tagged)

['London', ',', 'Feb.', '9', '--', 'Vital', 'secrets', 'of', 'Britain', "'s", 'first', 'atomic', 'submarine', ',', 'the', 'Dreadnought', ',', 'and', ',', 'by', 'implication', ',', 'of', 'the', 'entire', 'United', 'States', 'navy', "'s", 'still-building', 'nuclear', 'sub', 'fleet', ',', 'were', 'stolen', 'by', 'a', 'London-based', 'soviet', 'spy', 'ring', ',', 'secret', 'service', 'agents', 'testified', 'today', '.', 'The', 'Dreadnought', 'was', 'built', 'on', 'designs', 'supplied', 'by', 'the', 'United', 'States', 'in', '1959', 'and', 'was', 'launched', 'last', 'year', '.', 'It', 'is', 'a', 'killer', 'sub', '--', 'that', 'is', ',', 'a', 'hunter', 'of', 'enemy', 'subs', '.', 'It', 'has', 'a', 'hull', 'patterned', 'on', 'that', 'of', 'the', 'United', 'States', 'navy', "'s", 'Nautilus', ',', 'the', 'world', "'s", 'first', 'atomic', 'submarine', '.', 'Its', 'power', 'unit', ',', 'however', ',', 'was', 'derived', 'from', 'the', 'reactor', 'of', 'the', 'more', 'modern', 'American', 'nuclear'

[('London', 'NNP'), (',', ','), ('Feb.', 'NNP'), ('9', 'CD'), ('--', ':'), ('Vital', 'JJ'), ('secrets', 'NNS'), ('of', 'IN'), ('Britain', 'NNP'), ("'s", 'POS'), ('first', 'JJ'), ('atomic', 'JJ'), ('submarine', 'NN'), (',', ','), ('the', 'DT'), ('Dreadnought', 'NNP'), (',', ','), ('and', 'CC'), (',', ','), ('by', 'IN'), ('implication', 'NN'), (',', ','), ('of', 'IN'), ('the', 'DT'), ('entire', 'JJ'), ('United', 'NNP'), ('States', 'NNPS'), ('navy', 'VBP'), ("'s", 'POS'), ('still-building', 'JJ'), ('nuclear', 'JJ'), ('sub', 'NN'), ('fleet', 'NN'), (',', ','), ('were', 'VBD'), ('stolen', 'VBN'), ('by', 'IN'), ('a', 'DT'), ('London-based', 'JJ'), ('soviet', 'JJ'), ('spy', 'NN'), ('ring', 'NN'), (',', ','), ('secret', 'JJ'), ('service', 'NN'), ('agents', 'NNS'), ('testified', 'VBD'), ('today', 'NN'), ('.', '.'), ('The', 'DT'), ('Dreadnought', 'NNP'), ('was', 'VBD'), ('built', 'VBN'), ('on', 'IN'), ('designs', 'NNS'), ('supplied', 'VBN'), ('by', 'IN'), ('the', 'DT'), ('United', 'NNP'), ('Stat

In [17]:
#Stemming
from nltk.stem import LancasterStemmer
lancaster=LancasterStemmer()
print("Orignal Sentence:",str1)
print("\n")

str1 = [lancaster.stem(token) for token in str1.split(" ")]
print("Stemmed Sentence:")
print(" ".join(str1))

Orignal Sentence: London , Feb. 9 -- Vital secrets of Britain's first atomic submarine , the Dreadnought , and , by implication , of the entire United States navy's still-building nuclear sub fleet , were stolen by a London-based soviet spy ring , secret service agents testified today . The Dreadnought was built on designs supplied by the United States in 1959 and was launched last year . It is a killer sub -- that is , a hunter of enemy subs . It has a hull patterned on that of the United States navy's Nautilus , the world's first atomic submarine . Its power unit , however , was derived from the reactor of the more modern American nuclear submarine Skipjack . Five held for trial The announcement that the secrets of the Dreadnought had been stolen was made in Bow St. police court here at the end of a three day hearing . A full trial was ordered for : Two British civil servants , Miss Ethel Gee , 46 , and her newly devoted friend , Harry Houghton , 55 , and divorced . They are accused 